-- Create table for superfund site data import:
CREATE TABLE superfund_data_table (
	id								SERIAL PRIMARY KEY,
	address							VARCHAR,
	city							VARCHAR,
	latitude						FLOAT,
	longitude						FLOAT,
	site_score						FLOAT,
	site_text						TEXT,
	State_name						VARCHAR,
	County_name						VARCHAR,
	Tract							INT,
	Block_Group						INT,
	Tot_Population_CEN_2010			FLOAT,
	Hispanic_CEN_2010				FLOAT,
	NH_Blk_alone_CEN_2010			FLOAT,
	NH_AIAN_alone_CEN_2010			FLOAT,
	NH_Asian_alone_CEN_2010			FLOAT,
	NH_NHOPI_alone_CEN_2010			FLOAT,
	NH_SOR_alone_CEN_2010			FLOAT,
	College_ACS_09_13				FLOAT,
	No_Health_Ins_ACS_09_13			FLOAT,
	Med_HHD_Inc_BG_ACS_09_13		FLOAT,
	Aggregate_HH_INC_ACS_09_13		FLOAT,
	Tot_Vacant_Units_CEN_2010		FLOAT,
	Renter_Occp_HU_CEN_2010			FLOAT,
	Owner_Occp_HU_CEN_2010			FLOAT,
	No_Plumb_ACS_09_13				FLOAT,
	Med_House_Value_BG_ACS_09_13	FLOAT,
	pct_Hispanic_CEN_2010			FLOAT,
	pct_NH_Blk_alone_CEN_2010		FLOAT,
	pct_NH_AIAN_alone_CEN_2010		FLOAT,
	pct_NH_Asian_alone_CEN_2010		FLOAT,
	pct_NH_NHOPI_alone_CEN_2010		FLOAT,
	pct_NH_SOR_alone_CEN_2010		FLOAT,
	pct_Not_HS_Grad_ACS_09_13		FLOAT,
	pct_No_Health_Ins_ACS_09_13		FLOAT,
	pct_Vacant_Units_CEN_2010		FLOAT,
	pct_Renter_Occp_HU_CEN_2010		FLOAT,
	pct_Owner_Occp_HU_CEN_2010		FLOAT,
	pct_No_Plumb_ACS_09_13			FLOAT
);
-- Create table for superfund site data after analysis:
CREATE TABLE superfund_analysis_table (
	id								SERIAL PRIMARY KEY,
	address							VARCHAR,
	city							VARCHAR,
	latitude						FLOAT,
	longitude						FLOAT,
	site_score						FLOAT,
	site_text						TEXT,
	State_name						VARCHAR,
	County_name						VARCHAR,
	Tract							INT,
	Block_Group						INT,
	Tot_Population_CEN_2010			FLOAT,
	Hispanic_CEN_2010				FLOAT,
	NH_Blk_alone_CEN_2010			FLOAT,
	NH_AIAN_alone_CEN_2010			FLOAT,
	NH_Asian_alone_CEN_2010			FLOAT,
	NH_NHOPI_alone_CEN_2010			FLOAT,
	NH_SOR_alone_CEN_2010			FLOAT,
	College_ACS_09_13				FLOAT,
	No_Health_Ins_ACS_09_13			FLOAT,
	Med_HHD_Inc_BG_ACS_09_13		FLOAT,
	Aggregate_HH_INC_ACS_09_13		FLOAT,
	Tot_Vacant_Units_CEN_2010		FLOAT,
	Renter_Occp_HU_CEN_2010			FLOAT,
	Owner_Occp_HU_CEN_2010			FLOAT,
	No_Plumb_ACS_09_13				FLOAT,
	Med_House_Value_BG_ACS_09_13	FLOAT,
	pct_Hispanic_CEN_2010			FLOAT,
	pct_NH_Blk_alone_CEN_2010		FLOAT,
	pct_NH_AIAN_alone_CEN_2010		FLOAT,
	pct_NH_Asian_alone_CEN_2010		FLOAT,
	pct_NH_NHOPI_alone_CEN_2010		FLOAT,
	pct_NH_SOR_alone_CEN_2010		FLOAT,
	pct_Not_HS_Grad_ACS_09_13		FLOAT,
	pct_No_Health_Ins_ACS_09_13		FLOAT,
	pct_Vacant_Units_CEN_2010		FLOAT,
	pct_Renter_Occp_HU_CEN_2010		FLOAT,
	pct_Owner_Occp_HU_CEN_2010		FLOAT,
	pct_No_Plumb_ACS_09_13			FLOAT,
	pct_poc							FLOAT
);